@extends('layouts.app')

@section('auth')
    @if (\Request::is('dashboard'))
        @include('layouts.navbars.auth.nav-guest')
        @yield('content')
    @elseif (\Request::is('login'))
        @include('layouts.navbars.auth.nav-guest-login')
        @yield('content')
    @elseif (\Request::is('register'))
        @include('layouts.navbars.auth.nav-guest-login')
        @yield('content')
    @elseif (\Request::is('dashboard-admin'))
        @include('layouts.navbars.auth.nav-admin')
        @yield('content')
    @elseif(\Request::is('tables-admin'))
        @include('layouts.navbars.auth.nav-admin')
        @yield('content')
    @elseif(\Request::is('mahasiswa/edit/*'))
        @include('layouts.navbars.auth.nav-admin')
        @yield('content')
    @elseif(\Request::is('details/*'))
        @include('layouts.navbars.auth.nav-admin')
        @yield('content')
    @elseif (\Request::is('dashboard-mhs'))
        @include('layouts.navbars.auth.nav-mhs')
        @yield('content')
    @elseif(\Request::is('tables'))
        @include('layouts.navbars.auth.nav-mhs')
        @yield('content')
    @elseif(\Request::is('mahasiswa'))
        @include('layouts.navbars.auth.nav-mhs')
        @yield('content')
        {{-- @elseif(\Request::is('profile'))
        @include('layouts.navbars.auth.nav-mhs')
        @yield('content') --}}
    @elseif(\Request::is('mahasiswa/create'))
        @include('layouts.navbars.auth.nav-mhs')
        @yield('content')
    @endif

    @include('components.fixed-plugin')
@endsection
